name: meme_generator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  drift: ^2.15.0
  share_plus: ^7.2.2
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  sqlite3: ^2.4.0
  screenshot: ^2.1.0
  file_picker: ^6.1.1
  permission_handler: ^11.3.0
  dio: ^5.4.1
  bloc: ^8.1.4
  dynamic_color: ^1.7.0
  go_router: ^13.2.4
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5

dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  go_router_builder: ^2.5.1
  build_verify: ^3.1.0
flutter:
  uses-material-design: true
